export default {
  Menu: {
    items: [
      { title: `Fotografia ślubna`, src: `slub`, component: `Wedding` },
      { title: `Fotografia dziecięca`, src: `dzieci`, component: `Children` },
      { title: `Fotografia portretowa`, src: `portret`, component: `Portrait` },
      { title: `Oferta`, src: `oferta`, component: `Offer` },
      { title: `Kontakt`, src: `kontakt`, component: `Contact` },
    ],
  },
  Homepage: {
    title: `Anna Chowaniec Portfolio`,
    images: [
      { src: `/images/photos/splash/DSC_0087.jpg`, title: `title photo 1` },
      { src: `/images/photos/splash/DSC_0901.jpg`, title: `title photo 2` },
      { src: `/images/photos/splash/DSC_1881.jpg`, title: `title photo 3` },
    ],
  },
  About: {
    image: { src: `/images/photos/me.jpg`, title: `Anna Chowaniec` },
    description: `Anna Chowaniec. Opis.`,
  },
  Pages: [],
  Photos: [],
  Wedding: {
    images: [
      {
        src: `/images/photos/wedding/slub_1.jpg`,
        title: `Wedding 1`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/wedding/slub_2.jpg`,
        title: `Wedding 2`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/wedding/slub_3.jpg`,
        title: `Wedding 3`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/wedding/slub_4.jpg`,
        title: `Wedding 4`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/wedding/slub_5.jpg`,
        title: `Wedding 5`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/wedding/slub_6.jpg`,
        title: `Wedding 6`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/wedding/slub_7.jpg`,
        title: `Wedding 7`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/wedding/slub_8.jpg`,
        title: `Wedding 8`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/wedding/slub_9.jpg`,
        title: `Wedding 9`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/wedding/slub_10.jpg`,
        title: `Wedding 10`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/wedding/slub_11.jpg`,
        title: `Wedding 11`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/wedding/slub_12.jpg`,
        title: `Wedding 12`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/wedding/slub_13.jpg`,
        title: `Wedding 13`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/wedding/slub_14.jpg`,
        title: `Wedding 14`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/wedding/slub_15.jpg`,
        title: `Wedding 15`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/wedding/slub_16.jpg`,
        title: `Wedding 16`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/wedding/slub_17.jpg`,
        title: `Wedding 17`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/wedding/slub_18.jpg`,
        title: `Wedding 18`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/wedding/slub_19.jpg`,
        title: `Wedding 19`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/wedding/slub_20.jpg`,
        title: `Wedding 20`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/wedding/slub_21.jpg`,
        title: `Wedding 21`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/wedding/slub_22.jpg`,
        title: `Wedding 22`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/wedding/slub_23.jpg`,
        title: `Wedding 23`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/wedding/slub_24.jpg`,
        title: `Wedding 24`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/wedding/slub_25.jpg`,
        title: `Wedding 25`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/wedding/slub_26.jpg`,
        title: `Wedding 26`,
        width: 3,
        height: 2,
      },
    ],
  },
  Children: {
    images: [
      {
        src: `/images/photos/children/dzieci_1.jpg`,
        title: `Child 1`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/children/dzieci_2.jpg`,
        title: `Child 2`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_3.jpg`,
        title: `Child 3`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/children/dzieci_4.jpg`,
        title: `Child 4`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_5.jpg`,
        title: `Child 5`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/children/dzieci_6.jpg`,
        title: `Child 6`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_7.jpg`,
        title: `Child 7`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_8.jpg`,
        title: `Child 8`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/children/dzieci_9.jpg`,
        title: `Child 9`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_10.jpg`,
        title: `Child 10`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_11.jpg`,
        title: `Child 11`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_12.jpg`,
        title: `Child 12`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_13.jpg`,
        title: `Child 13`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_14.jpg`,
        title: `Child 14`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_15.jpg`,
        title: `Child 15`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/children/dzieci_16.jpg`,
        title: `Child 16`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_17.jpg`,
        title: `Child 17`,
        width: 5,
        height: 3,
      },
      {
        src: `/images/photos/children/dzieci_18.jpg`,
        title: `Child 18`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_19.jpg`,
        title: `Child 19`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_20.jpg`,
        title: `Child 20`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_21.jpg`,
        title: `Child 21`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_22.jpg`,
        title: `Child 22`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_23.jpg`,
        title: `Child 23`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_24.jpg`,
        title: `Child 24`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_25.jpg`,
        title: `Child 25`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_26.jpg`,
        title: `Child 26`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_27.jpg`,
        title: `Child 27`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_28.jpg`,
        title: `Child 28`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_29.jpg`,
        title: `Child 29`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_30.jpg`,
        title: `Child 30`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_31.jpg`,
        title: `Child 31`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_32.jpg`,
        title: `Child 32`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_33.jpg`,
        title: `Child 33`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_34.jpg`,
        title: `Child 34`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/children/dzieci_35.jpg`,
        title: `Child 35`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_36.jpg`,
        title: `Child 36`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_37.jpg`,
        title: `Child 37`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_38.jpg`,
        title: `Child 38`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_39.jpg`,
        title: `Child 39`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/children/dzieci_40.jpg`,
        title: `Child 40`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/children/dzieci_41.jpg`,
        title: `Child 41`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/children/dzieci_42.jpg`,
        title: `Child 42`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/children/dzieci_43.jpg`,
        title: `Child 43`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_44.jpg`,
        title: `Child 44`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_45.jpg`,
        title: `Child 45`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_46.jpg`,
        title: `Child 46`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/children/dzieci_47.jpg`,
        title: `Child 47`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/children/dzieci_48.jpg`,
        title: `Child 48`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_49.jpg`,
        title: `Child 49`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/children/dzieci_50.jpg`,
        title: `Child 50`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/dzieci_51.jpg`,
        title: `Child 51`,
        width: 3,
        height: 2,
      },
    ],
  },
};
