export default {
  Menu: {
    items: [
      { title: `Fotografia ślubna`, src: `slub`, component: `Wedding` },
      { title: `Fotografia dziecięca`, src: `dzieci`, component: `Children` },
      { title: `Fotografia portretowa`, src: `portret`, component: `Portrait` },
      { title: `Oferta`, src: `oferta`, component: `Offer` },
      { title: `Kontakt`, src: `kontakt`, component: `Contact` },
    ],
  },
  Homepage: {
    title: `Anna Chowaniec Portfolio`,
    images: [
      { src: `/images/photos/splash/DSC_0087.jpg`, title: `title photo 1` },
      { src: `/images/photos/splash/DSC_0901.jpg`, title: `title photo 2` },
      { src: `/images/photos/splash/DSC_1881.jpg`, title: `title photo 3` },
    ],
  },
  About: {
    image: { src: `/images/photos/me.jpg`, title: `Anna Chowaniec` },
    description: `Hej, nazywam się Anna Chowaniec i jestem fotografem.`,
  },
  Children: {
    images: [
      {
        src: `/images/photos/children/DSC_0082.jpg`,
        title: `Child 1`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/children/DSC_4010.jpg`,
        title: `Child 2`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_6601.jpg`,
        title: `Child 3`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_8744.jpg`,
        title: `Child 4`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/children/DSC_9894.jpg`,
        title: `Child 5`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/children/DSC_0087.jpg`,
        title: `Child 6`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_4045.jpg`,
        title: `Child 7`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_6655.jpg`,
        title: `Child 8`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/children/DSC_8747.jpg`,
        title: `Child 9`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_9895.jpg`,
        title: `Child 10`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_0126.jpg`,
        title: `Child 11`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_4074.jpg`,
        title: `Child 12`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_6686.jpg`,
        title: `Child 13`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_8779.jpg`,
        title: `Child 14`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_9906.jpg`,
        title: `Child 15`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_0143.jpg`,
        title: `Child 16`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/children/DSC_6085.jpg`,
        title: `Child 17`,
        width: 4,
        height: 3,
      },
      {
        src: `/images/photos/children/DSC_6711.jpg`,
        title: `Child 18`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_8817.jpg`,
        title: `Child 19`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_9909.jpg`,
        title: `Child 20`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/children/DSC_0216.jpg`,
        title: `Child 21`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_6304.jpg`,
        title: `Child 22`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_8425.jpg`,
        title: `Child 23`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_9187.jpg`,
        title: `Child 24`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/children/DSC_9926.jpg`,
        title: `Child 25`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_0217aa.jpg`,
        title: `Child 26`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_6484.jpg`,
        title: `Child 27`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_8439.jpg`,
        title: `Child 28`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_9216.jpg`,
        title: `Child 29`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/children/DSC_9928.jpg`,
        title: `Child 30`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_0225.jpg`,
        title: `Child 31`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_6513.jpg`,
        title: `Child 32`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_8453.jpg`,
        title: `Child 33`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_9830.jpg`,
        title: `Child 34`,
        width: 4,
        height: 3,
      },
      {
        src: `/images/photos/children/DSC_9945.jpg`,
        title: `Child 35`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/children/DSC_0528.jpg`,
        title: `Child 36`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_6519.jpg`,
        title: `Child 37`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_8458.jpg`,
        title: `Child 38`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_9848.jpg`,
        title: `Child 39`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/children/DSC_0557.jpg`,
        title: `Child 40`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_6525.jpg`,
        title: `Child 41`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_8632.jpg`,
        title: `Child 42`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/children/DSC_9864.jpg`,
        title: `Child 43`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_0572.jpg`,
        title: `Child 44`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_6555.jpg`,
        title: `Child 45`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_8636.jpg`,
        title: `Child 46`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/children/DSC_9870.jpg`,
        title: `Child 47`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_0611.jpg`,
        title: `Child 48`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_6585.jpg`,
        title: `Child 49`,
        width: 3,
        height: 2,
      },
      {
        src: `/images/photos/children/DSC_8695.jpg`,
        title: `Child 50`,
        width: 2,
        height: 3,
      },
      {
        src: `/images/photos/children/DSC_9876.jpg`,
        title: `Child 51`,
        width: 3,
        height: 2,
      },
    ],
  },
};
